kind: pipeline
name: test

steps:
- name: docker-test
  image: docker:dind
  volumes:
    - name: dockersock
      path: /var/run
  environment:
    KEY_FILE:
      from_secret: key
  commands:
    - echo $KEY_FILE

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}